In [1]:
import numpy as np

In [3]:
type([1,2,3])

list

In [5]:
arreglo_np = np.array([1,2,3])

In [6]:
type(arreglo_np)

numpy.ndarray

In [7]:
tupla_np = np.array((1,2,3,4))

In [8]:
type(tupla_np)

numpy.ndarray

In [9]:
np.zeros((1))

array([0.])

In [10]:
np.zeros((5))

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros((5,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [19]:
np.ones((3,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [25]:
np.empty((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [24]:
np.eye((4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [28]:
np.arange(3,10,2)

array([3, 5, 7, 9])

In [29]:
arreglo_pares = np.arange(0,20,2)

In [30]:
arreglo_pares.size

10

In [31]:
arreglo_pare

(10,)

In [33]:
arreglo_pares.reshape((2,5))

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [34]:
np.arange(24).reshape((6,2,2))

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23]]])

In [36]:
np.arange(100000).reshape(10000,10)

array([[    0,     1,     2, ...,     7,     8,     9],
       [   10,    11,    12, ...,    17,    18,    19],
       [   20,    21,    22, ...,    27,    28,    29],
       ...,
       [99970, 99971, 99972, ..., 99977, 99978, 99979],
       [99980, 99981, 99982, ..., 99987, 99988, 99989],
       [99990, 99991, 99992, ..., 99997, 99998, 99999]])

In [52]:
a = np.array([10,10,10])
b = np.array((5,5,5))

In [41]:
#Suma
print (a+b)

[15 15 15]


In [43]:
#Resta
a-b

array([5, 5, 5])

In [44]:
#Multiplicacion
a*b

array([50, 50, 50])

In [45]:
#division
a/b

array([2., 2., 2.])

In [46]:
#Modulo
a%b

array([0, 0, 0])

In [47]:
a/2

array([5., 5., 5.])

In [49]:
np.sqrt(a)

array([3.16227766, 3.16227766, 3.16227766])

In [55]:
arreglo_doce = np.arange(12)
arreglo_doce

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [54]:
arreglo_doce>5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True])

In [56]:
A = np.arange(4).reshape((2,2))
A

array([[0, 1],
       [2, 3]])

In [57]:
B = np.arange(4,8).reshape((2,2))
B

array([[4, 5],
       [6, 7]])

In [58]:
A*B

array([[ 0,  5],
       [12, 21]])

In [59]:
A.dot(B)

array([[ 6,  7],
       [26, 31]])

In [60]:
np.dot(A,B)

array([[ 6,  7],
       [26, 31]])

In [64]:
RESULTADO = np.arange(4).reshape(2,2)
np.dot(A,B,RESULTADO)

array([[ 6,  7],
       [26, 31]])

In [65]:
RESULTADO

array([[ 6,  7],
       [26, 31]])

In [67]:
arreglo_tres = np.arange(3)
arreglo_tres +=2

In [68]:
arreglo_tres

array([2, 3, 4])

In [69]:
arreglo_tres.sum()

9

In [70]:
arreglo_tres.min()

2

In [71]:
arreglo_tres.max()

4

In [77]:
arreglo_tres_cuatro = np.arange(24).reshape(6,2,2)
arreglo_tres_cuatro

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23]]])

In [78]:
arreglo_tres_cuatro.sum(axis=0)

array([[60, 66],
       [72, 78]])

In [79]:
arreglo_tres_cuatro.sum(axis=1)

array([[ 2,  4],
       [10, 12],
       [18, 20],
       [26, 28],
       [34, 36],
       [42, 44]])

In [80]:
arreglo_tres_cuatro.sum(axis=2)

array([[ 1,  5],
       [ 9, 13],
       [17, 21],
       [25, 29],
       [33, 37],
       [41, 45]])