# Indices

In [1]:
import numpy as np

In [4]:
numeros = np.arange(11)**2

In [5]:
numeros

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [6]:
indices =[2,5,7] 

In [7]:
numeros[indices]

array([ 4, 25, 49])

In [19]:
arreglo_frutas = np.array([
    ['Piña','Manzana','Pera','Melón'],
    ['Pera','Uva', 'Naranja', 'Papaya'],
    ['Frutilla','Plátano','Granadilla','Sandía']
])

In [20]:
arreglo_frutas.shape

(3, 4)

In [26]:
arreglo_filas = np.array([
    [0,0],
    [1,1],
    [2,2],
])
arreglo_filas

array([[0, 0],
       [1, 1],
       [2, 2]])

In [28]:
arreglo_columnas = np.array([
    [2,3],
    [2,3],
    [2,3],
])
arreglo_columnas

array([[2, 3],
       [2, 3],
       [2, 3]])

In [29]:
arreglo_frutas[arreglo_filas,arreglo_columnas]

array([['Pera', 'Melón'],
       ['Naranja', 'Papaya'],
       ['Granadilla', 'Sandía']], dtype='<U10')

In [17]:
arreglo_frutas

array([['Piña', 'Manzana', 'Pera', 'Melón'],
       ['Pera', 'Uva', 'Naranja', 'Papaya'],
       ['Frutilla', 'Plátano', 'Granadilla', 'Sandía']], dtype='<U10')

In [66]:
arreglo_tridimensional_frutas = np.array(['Piña','Manzana','Pera','Melón','Pera','Uva', 'Naranja', 'Papaya','Frutilla','Plátano','Granadilla','Sandía',
                                          'Arándanos','Banano','Kiwi','Pitahaya','Tomate','Granada','Guanabana','Naranjilla','Maracuya','Durazno','Babaco',
                                          'Mora'])

In [67]:
arreglo_trid = arreglo_tridimensional_frutas.reshape(4,3,2)

In [68]:
arreglo_trid

array([[['Piña', 'Manzana'],
        ['Pera', 'Melón'],
        ['Pera', 'Uva']],

       [['Naranja', 'Papaya'],
        ['Frutilla', 'Plátano'],
        ['Granadilla', 'Sandía']],

       [['Arándanos', 'Banano'],
        ['Kiwi', 'Pitahaya'],
        ['Tomate', 'Granada']],

       [['Guanabana', 'Naranjilla'],
        ['Maracuya', 'Durazno'],
        ['Babaco', 'Mora']]], dtype='<U10')

In [73]:
#Solo puede tener valores de 0 a 3
arreglo_filas_trid = np.array([1,3])

In [74]:
#Solo puede tener valores de 0 a 2
arreglo_col_trid = np.array([1,1])

In [75]:
#Solo puede tener valores de 0 a 1
arreglo_z_trid = np.array([0,1])

In [76]:
# Para obtener frutilla y durazno
arreglo_trid[arreglo_filas_trid,arreglo_col_trid,arreglo_z_trid]

array(['Frutilla', 'Durazno'], dtype='<U10')

In [78]:
arreglo_tetradimensional = np.arange(48)

In [84]:
arreglo_tetra = arreglo_tetradimensional.reshape(4,3,2,2)
print(arreglo_tetra)

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]

  [[ 8  9]
   [10 11]]]


 [[[12 13]
   [14 15]]

  [[16 17]
   [18 19]]

  [[20 21]
   [22 23]]]


 [[[24 25]
   [26 27]]

  [[28 29]
   [30 31]]

  [[32 33]
   [34 35]]]


 [[[36 37]
   [38 39]]

  [[40 41]
   [42 43]]

  [[44 45]
   [46 47]]]]


In [86]:
pri_tetra = np.array([0,2])
seg_tetra = np.array([2,2])
ter_tetra = np.array([1,1])
cua_tetra = np.array([0,1])


In [87]:
arreglo_tetra[pri_tetra,seg_tetra,ter_tetra,cua_tetra]

array([10, 35])