In [1]:
import numpy as np

1. Crear un arreglo de 20 elementos.

In [2]:
arreglo_veinte = np.arange(20)
print(arreglo_veinte)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


1.2. Cambiar la dimensión del arreglo previamente creado.

In [4]:
arreglo_veinte.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

1.3. Inprimir los números pares en el arreglo anterior.

In [8]:
indice_pares = (arreglo_veinte % 2==0)
print(arreglo_veinte[indice_pares])

[ 0  2  4  6  8 10 12 14 16 18]


1.4. Obtener la suma de todos los números pares del arreglo

In [11]:
arreglo_pares = arreglo_veinte[indice_pares]
arreglo_pares.sum()

90

1.5. Obtener el seno de los elementos del primer arreglo creado

In [14]:
np.sin(arreglo_veinte)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721])

1.6. Obtener el coseno de los elementos del primer arreglo creado

In [15]:
np.cos(arreglo_veinte)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153,  0.0044257 ,  0.84385396,  0.90744678,  0.13673722,
       -0.75968791, -0.95765948, -0.27516334,  0.66031671,  0.98870462])

1.7. Obtener la tangente de los elementos del primer arreglo creado

In [16]:
np.tan(arreglo_veinte)

array([ 0.00000000e+00,  1.55740772e+00, -2.18503986e+00, -1.42546543e-01,
        1.15782128e+00, -3.38051501e+00, -2.91006191e-01,  8.71447983e-01,
       -6.79971146e+00, -4.52315659e-01,  6.48360827e-01, -2.25950846e+02,
       -6.35859929e-01,  4.63021133e-01,  7.24460662e+00, -8.55993401e-01,
        3.00632242e-01,  3.49391565e+00, -1.13731371e+00,  1.51589471e-01])

2. Crear un arreglo de marca de licores

In [25]:
arreglo_licores = np.array(['Cantaclaro','José Cuervo','Under','Sky','Ruskaya','Azteca','Antioqueño','Tropico',
                  'Norteño', 'Paisa','Zhumir','Pedrito Coco','Chivas','Jack Daniels','Punta','Bacardi',
                  '100 fuegos','Grants','El Charro','Abuelo','Legendario','Jaggermeister','Bombay','Absolute'] )

In [26]:
arreglo_licores.shape

(24,)

2.1 dividir el arreglo en tres formas diferentes

In [28]:
arreglo_licores_1 = arreglo_licores.reshape(12,2)
print(arreglo_licores_1)

[['Cantaclaro' 'José Cuervo']
 ['Under' 'Sky']
 ['Ruskaya' 'Azteca']
 ['Antioqueño' 'Tropico']
 ['Norteño' 'Paisa']
 ['Zhumir' 'Pedrito Coco']
 ['Chivas' 'Jack Daniels']
 ['Punta' 'Bacardi']
 ['100 fuegos' 'Grants']
 ['El Charro' 'Abuelo']
 ['Legendario' 'Jaggermeister']
 ['Bombay' 'Absolute']]


In [29]:
arreglo_licores_2 = arreglo_licores.reshape(6,2,2)
print(arreglo_licores_2)

[[['Cantaclaro' 'José Cuervo']
  ['Under' 'Sky']]

 [['Ruskaya' 'Azteca']
  ['Antioqueño' 'Tropico']]

 [['Norteño' 'Paisa']
  ['Zhumir' 'Pedrito Coco']]

 [['Chivas' 'Jack Daniels']
  ['Punta' 'Bacardi']]

 [['100 fuegos' 'Grants']
  ['El Charro' 'Abuelo']]

 [['Legendario' 'Jaggermeister']
  ['Bombay' 'Absolute']]]


In [31]:
arreglo_licores_3 = arreglo_licores.reshape(6,2,2,1)
print(arreglo_licores_3)

[[[['Cantaclaro']
   ['José Cuervo']]

  [['Under']
   ['Sky']]]


 [[['Ruskaya']
   ['Azteca']]

  [['Antioqueño']
   ['Tropico']]]


 [[['Norteño']
   ['Paisa']]

  [['Zhumir']
   ['Pedrito Coco']]]


 [[['Chivas']
   ['Jack Daniels']]

  [['Punta']
   ['Bacardi']]]


 [[['100 fuegos']
   ['Grants']]

  [['El Charro']
   ['Abuelo']]]


 [[['Legendario']
   ['Jaggermeister']]

  [['Bombay']
   ['Absolute']]]]


2.2 Obtener la transpuesta del arreglo_licores_1

In [33]:
arreglo_licores_1.T

array([['Cantaclaro', 'Under', 'Ruskaya', 'Antioqueño', 'Norteño',
        'Zhumir', 'Chivas', 'Punta', '100 fuegos', 'El Charro',
        'Legendario', 'Bombay'],
       ['José Cuervo', 'Sky', 'Azteca', 'Tropico', 'Paisa',
        'Pedrito Coco', 'Jack Daniels', 'Bacardi', 'Grants', 'Abuelo',
        'Jaggermeister', 'Absolute']], dtype='<U13')

2.3 Transformar el arreglo_licores_3 en una sola dimensión

In [32]:
arreglo_licores_3.flatten()

array(['Cantaclaro', 'José Cuervo', 'Under', 'Sky', 'Ruskaya', 'Azteca',
       'Antioqueño', 'Tropico', 'Norteño', 'Paisa', 'Zhumir',
       'Pedrito Coco', 'Chivas', 'Jack Daniels', 'Punta', 'Bacardi',
       '100 fuegos', 'Grants', 'El Charro', 'Abuelo', 'Legendario',
       'Jaggermeister', 'Bombay', 'Absolute'], dtype='<U13')

2.4 Dividir el arreglo licores en dos y guardarlos en nuevos arreglos

In [35]:
licores_mitad1, licores_mitad2 = np.split(arreglo_licores,2)

In [36]:
licores_mitad1

array(['Cantaclaro', 'José Cuervo', 'Under', 'Sky', 'Ruskaya', 'Azteca',
       'Antioqueño', 'Tropico', 'Norteño', 'Paisa', 'Zhumir',
       'Pedrito Coco'], dtype='<U13')

In [37]:
 licores_mitad2

array(['Chivas', 'Jack Daniels', 'Punta', 'Bacardi', '100 fuegos',
       'Grants', 'El Charro', 'Abuelo', 'Legendario', 'Jaggermeister',
       'Bombay', 'Absolute'], dtype='<U13')

2.5 del arreglo licores_2 obtener los licores Antioqueño y Bacardi

In [38]:
arreglo_x = np.array([1,3])
arreglo_y = np.array([1,1])
arreglo_z = np.array([1,1])

In [39]:
arreglo_licores_2[arreglo_x,arreglo_y,arreglo_z]

array(['Tropico', 'Tropico'], dtype='<U13')